swagger: '2.0'
info:
  version: 0.0.1
  title: deployment
  description: >-
    A service to store deployment, value, type information. All of them are stored as Strings.
  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: Cloudmesh RESTful Service Example
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: 'localhost:8080'
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/deployments:
    get:
      description: Returns all deployments
      operationId: get_deployment
      produces:
        - application/json
      responses:
        '200':
          description: deployment info
          schema:
            $ref: '#/definitions/Deployment'
    put:
      summary: Create a new deployment
      operationId: add_deployment
      parameters:
        - in: body
          name: deployment
          description: The new deployment to create
          schema:
            $ref: '#/definitions/Deployment'
      responses:
        '201':
          description: Created
  '/cloudmesh/deployment/{name}':
    get:
      description: Returns a deployment
      operationId: get_deployment_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: deployment info
          schema:
            $ref: '#/definitions/Deployment'
definitions:
  Deployment:
    type: object
    description: the deployment
    properties:
      cluster:
        type: string
        description: the name of the cluster
      stack:
        type: array
        items:
           layers: string
        