swagger: "2.0"
info:
  version: 3.0.2
  x-date: 10-30-2018
  title: deployment
  description: |-
  
    A service to store deployment, value, type information. All of
    them are stored as Strings.

    * TODO: assign for review and improvement
    
  termsOfService: https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/deployments:
    get:
      description: Returns all deployments
      tags:
        - Deployment
      operationId: cloudmesh.deployment.get
      produces:
        - application/json
      responses:
        200:
          description: deployment info
          schema:
            $ref: '#/definitions/Deployment'
    put:
      summary: Create a new deployment
      tags:
        - Deployment
      operationId: cloudmesh.deployment.add
      parameters:
        - in: body
          name: deployment
          description: The new deployment to create
          schema:
            $ref: '#/definitions/Deployment'
      responses:
        '201':
          description: Created
  '/cloudmesh/deployment/{name}':
    get:
      description: Returns a deployment
      tags:
        - Deployment
      operationId: cloudmesh.deployment.get_by_name
      parameters:
        - name: name
          description: Get deployment info by name
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: deployment info
          schema:
            $ref: '#/definitions/Deployment'
definitions:
  Deployment:
    type: object
    description: the deployment
    properties:
      cluster:
        type: string
        description: the name of the cluster
      stack:
        type: array
        items:
           type: object
           #layers: string
      timestamp:
        description: timestamps associated with the resource
        $ref: '#/definitions/Timestamp'
